title: Modo Stealth
author:
  name: Ranesu

description: >
  Modo Stealth Ã© um blog pessoal focado em reviews de jogos e opiniÃµes sinceras sobre o mundo dos games. 
  Aqui, cada anÃ¡lise Ã© feita com um olhar crÃ­tico e apaixonado, explorando desde grandes lanÃ§amentos atÃ© pÃ©rolas escondidas. 
  Seja para descobrir um novo jogo ou debater tendÃªncias da indÃºstria, o Modo Stealth Ã© o espaÃ§o para quem gosta de jogar com estratÃ©gia â€“ ou simplesmente quer saber o que vale a pena jogar. ğŸ®

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark # or auto if you want it to switch with your system settings.
  date_format: "%d/%m/%Y"
social_links:
  #  - title: Minima Theme repository at GitHub
  #    icon: github
  #    url: "https://github.com/jekyll/minima"
    - title: Ranesu
      icon: x-twitter
      url: "https://x.com/ranesu_"
